### ISSUE TITLE
Zip does not contain Avalon

### ISSUE THREAD

**Issue by mottosso** [tokejepsen/avalon-environment#4]
Looks like GitHub doesn't include the submodule with a zip download. :(

It means the user will need to download and install Git before being able to use this. I think you might be able to make a GitHub Release, and then *that* zip may include the submodule. Alternatively, make a zip yourself and upload it to the release. Alternatively alternatively, upload it elsewhere, such as BinTray. Both of which could be automated via Travis.

**Comment by mottosso** [comment]
Releases does not appear to contain the submodule either..

- https://github.com/mottosso/avalon-environment/releases/tag/test

**Comment by tokejepsen** [comment]
Thanks for testing this out :)

No, the submodules do not get downloaded with the zip, but they will be initialized when running any of the entry points; https://github.com/tokejepsen/avalon-environment/blob/master/bin/launch_conda.bat#L45-L49.

Let me know if this does not happen for you.

**Comment by mottosso** [comment]
Aaah, I actually didn't even try that. Silly me. If I hadn't had inside knowledge about it being a submodule, I wouldn't have had this problem.
