### ISSUE TITLE
Installer transparency

### ISSUE THREAD

**Issue by mottosso** [tokejepsen/avalon-environment#5]
IMO the README should say what is being installed and where. That way, (1) the project can be uninstalled, (2) the user can determine whether some or all dependencies are already installed (but elsewhere, and if so how to use those instead) and (3) the user can determine whether there is enough disk space on the drive/partition things are being installed.

(2) could be overlooked I think, assuming it's for getting started and not production use.

**Comment by tokejepsen** [comment]
Good idea. I'll update the README with this information.

**Comment by tokejepsen** [comment]
I have tried to provide this information in the [About](https://github.com/tokejepsen/avalon-environment#about) section.

Let me know if there is something missing, or unclear.

**Comment by mottosso** [comment]
I think that looks good.

**Comment by tokejepsen** [comment]
Excellent, thanks again 😄
